### ISSUE TITLE
FPS autoCrystal Decrease

### ISSUE THREAD

**Issue by FlufferyAutism** [srgantmoomoo/postman#33]
Postman Version postmanplusplus1.2-2.100
Windows 10 running with a debloat script

Fps takes a major decrease from 220~ to under 60 fps when AutoCrystal is turned on 
only happens that low 
200 - 130 on single player
200-2 fps on mutliplayer

**Comment by srgantmoomoo** [comment]
Make sure the mode is not smart (I’m not sure if own lags u either). That’s probably the problem, it has to be set to all.

**Comment by FlufferyAutism** [comment]
alr ty thats the issue

**Comment by srgantmoomoo** [comment]
cool. i would fix... but i don't care enough about this anymore lol. maybe eventually.
