### ISSUE TITLE
Are you gonna make it for newer versions

### ISSUE THREAD

**Issue by waz86** [srgantmoomoo/postman#38]
Are you ever gonna make it for newer versions or at least make it work with viaforge, cuz it doesn't work with the newest version of viaforge that goes to 1.18.1

**Comment by DRNUMBER1** [comment]
Try having a visit in the discord server, developmwnt towards this client has been stopped.

You can also rebuild this your self as I believe most modules will work same for 1.18 but not sure.
This client is not recommended for 1.18 use as it lacks features for that version. Use other client for 1.18 like Meteor client.

**Comment by waz86** [comment]
Alright thx
