### ISSUE TITLE
Replay Mod Mixin

### ISSUE THREAD

**Issue by GerroPogi** [srgantmoomoo/postman#41]
It isn't letting me using Replay Mod. Please fix this.

**Comment by DRNUMBER1** [comment]
can you give the error output?

**Comment by srgantmoomoo** [comment]
I need the crash log. And more information in general, you can't just leave a really broad issue expecting me to already know everything that's going on. What os are you on? Postman version? Replay mod version? What other mods are being run? What error is it giving? Leaving the crash log would answer all of those questions... lol.

**Comment by DrFluffery** [comment]
True asf

**Comment by srgantmoomoo** [comment]
Giv crash log
