### ISSUE TITLE
AntiWeakness via ca

### ISSUE THREAD

**Issue by TwoThreeTwo** [srgantmoomoo/postman#47]
so, I want to try and make antiWeakness in the ca, but the jar keeps giving null pointer exception errors and not making the jar 'runnable' via IntelliJ or vs (vs code with java ik), but there are also a trillion errors for some reason. Do you still get errors in eclipse? 

I'm using java8, but I switch to Correto15 when I do Swing as well as Computer Science.

**Comment by srgantmoomoo** [comment]
hmmm... you run gradle setupdecompworkspace before anything right? after that you should be able to build without issues. i haven't used eclipse in quite a while so im not sure ab that. would you be able to send me a txt file of the errors your getting or a ss or something?

**Comment by TwoThreeTwo** [comment]
well, most of the errors on IntelliJ just show 'cannot resolve {char of some sort related to minecraft}', there's also forgegradle errors so I have to force download dependenices, then go to ide -> eclipse and then run that, but yeah for sure I can send an ss. (Yeah, I run Gradle setupdecompworkspace) 
![image](https://user-images.githubusercontent.com/83801755/161881045-72d08c94-9d25-463a-bde9-e3507d9b62be.png)
this just shows the error I'm reciving. (happens on 98% of the classes btw)

**Comment by srgantmoomoo** [comment]
huh... that's interesting. i'm not really too sure why that is... :/

**Comment by TwoThreeTwo** [comment]
oof, well ig I can figure it out soon

**Comment by srgantmoomoo** [comment]
ill look into it a bit myself. thanks for reporting it :)

**Comment by TwoThreeTwo** [comment]
if you find a solution, re-open the issue bc I'll get notified

**Comment by TwoThreeTwo** [comment]
I discovered the issue :).
It's fixed sorry about that lol

**Comment by TwoThreeTwo** [comment]
I just had to invalidate caches and restart intelliJ

**Comment by srgantmoomoo** [comment]
Ah ok awesome!
