### ISSUE TITLE
ESP Crashes game

### ISSUE THREAD

**Issue by DrFluffery** [srgantmoomoo/postman#52]
Minecraft 1.12.2
Forge 14.23.5.2860
LWJGL 2 2.9.4-nightly-20150209

mods
dependency mods
baritone
3 hud element mods made by ppl idk
ghost writer
hwyla
ghost writer
journey map
mailman client (may or may not use moo base)
postman client
wdlforge

resource packs (might have causes idk)
Walter Totem
Fluffery's Faithful 32x

[crash-2022-04-24_22.00.00-client.txt](https://github.com/srgantmoomoo/postman/files/8551157/crash-2022-04-24_22.00.00-client.txt)

**Comment by TwoThreeTwo** [comment]
there's a issue srgantmoomoo posted about esp crashing with toggle command or something, if you want to use postman, skip to a commit before the commands :)

**Comment by TwoThreeTwo** [comment]
if you're using moobase, you should rename JCenter() to mavenCentral() because JCentral() is depricated since febuary 1st 2022 :)

**Comment by TwoThreeTwo** [comment]
![image](https://user-images.githubusercontent.com/83801755/165019151-09ce008d-1297-4f36-86ba-11accba2933f.png)
blame him

**Comment by DrFluffery** [comment]
Done back in january

**Comment by srgantmoomoo** [comment]
Who is okayik 😳

**Comment by TwoThreeTwo** [comment]
> Minecraft 1.12.2 Forge 14.23.5.2860 LWJGL 2 2.9.4-nightly-20150209
> 
> mods dependency mods baritone 3 hud element mods made by ppl idk ghost writer hwyla ghost writer journey map mailman client (may or may not use moo base) postman client wdlforge
> 
> resource packs (might have causes idk) Walter Totem Fluffery's Faithful 32x
> 
> [crash-2022-04-24_22.00.00-client.txt](https://github.com/srgantmoomoo/postman/files/8551157/crash-2022-04-24_22.00.00-client.txt)

can you send your latest.log, please?clear any info that might contain your irl name and such and such

**Comment by TwoThreeTwo** [comment]
NullpointerException with your error
